angular.module('app')
    .config(function($stateProvider,$urlRouterProvider){
        $urlRouterProvider.otherwise('/home');
        $stateProvider
            .state('home',{
                url:'/home',
                templateUrl:'home/home.html',
                controller:"HomeCtrl"
            })
            .state('about',{
                url:'/about',
                templateUrl:'about/about.html',
                controller:"AboutCtrl"
            })
            .state('bikram' , {
                url:'/bikram',
                templateUrl:'bikram/bikram.html',
                controller:'BikramCtrl',
            })
            .state('vince',{
                url:'/vince',
                templateUrl:"vince/vince.html",
                controller:"VinceCtrl"
            })            
            .state('mark',{
                url:'/mark',
                templateUrl:'mark/mark.html',
                controller:"MarkCtrl"
            })
            .state('joshua',{
                url:'/Joshua',
                templateUrl:'JB/Joshua.html',
                controller:"JBCtrl"
            })
            .state('josh',{
                url:'/josh',
                templateUrl:'josh/josh.html',
                controller:"JoshCtrl"
            })
            .state('agentsmith',{
            url:'/agentsmith',
            templateUrl:'agentsmith/agentsmith.html',
            controller:'AgentsmithCtrl'
            })
            .state('Goodwin',{
                url:'/Goodwin',
                templateUrl:'Goodwin/Goodwin.html',
                controller:"GoodwinCtrl"
            })
            .state('preston', {
                url:'/preston',
                templateUrl:'preston/preston.html',
                controller:'PrestonCtrl'
            })
            .state('senneca', {
                url:'/senneca',
                templateUrl:'senneca/senneca.html',
                controller:'SennecaCtrl'
            });
    });